### ISSUE TITLE
all Heroku builds are failing

### ISSUE THREAD

**Issue by jeffreywescott** [RocketChat/heroku-buildpack-meteor#5]
[It seems that the fine folks over at Meteor.com let their CERT expire!](https://forums.meteor.com/t/issue-with-packages-meteor-com-cert-has-expired-cant-deploy/25138/3)

File-under: WTF!?

**Comment by engelgabriel** [comment]
I have merger the changes from https://github.com/AdmitHub/meteor-buildpack-horse

This should be all fixed now. Please try setting `BUILDPACK_CLEAR_CACHE=1` on the environment variables configuration panel if it is still a problem for you.

In case the problem persists, please reopen this issue with more info.
