### ISSUE TITLE
Heroku build failing looking for 

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/heroku-buildpack-meteor#6]
Builds stopped working today, log below. Nothing in my config has change (that I'm aware of), I thought it might be something to do with recent Meteor version updates in RC. I'm still on v0.38.0 - is there a conflict between v0.39.0 and current develop branch of RC in regards to using the buildpack?

I haven't noticed the first steps before either, which are adding those env settings to my Heroku app config vars.

```
-----> Node.js app detected
-----> Listing HEROKU_ environment variables
HEROKU_APP_ID:           
HEROKU_APP_NAME:         
HEROKU_DYNO_ID:          
HEROKU_RELEASE_VERSION:  
HEROKU_SLUG_COMMIT:      
HEROKU_SLUG_DESCRIPTION: 
-----> Meteor version: Meteor 1.4.1.1
-----> Checking if this meteor version supports --server-only
-----> Attempting to remove android platform.
While removing platforms:
error: android: platform is not in this project
-----> Moving on.
cp: cannot stat ‘/app/tmp/cache/1.2.1/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node\n/app/tmp/cache/1.2.1/.meteor/packages/meteor-tool/.1.4.1_1.1t2uyaz++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node’: No such file or directory
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Comment by timkinnane** [comment]
FYI, I fixed my issue while writing it. I found someone with a [similar problem on another horse buildpack](https://github.com/AdmitHub/meteor-buildpack-horse/issues/133), solved by resetting the buildpack cache.

`heroku config:set BUILDPACK_CLEAR_CACHE=1`

Be warned, the next build will take a million years.

**Comment by engelgabriel** [comment]
Thanks @timkinnane I'll add this to the docs.
